export * from './characteristicsSection';
export * from './OperationDescriptionSection';
export * from './Footer';
export * from './applicationDescriptionSection';
export * from './TopBar';
export * from './HeroSection';
export * from './LogotipoAnimatedCarouselSection';
export * from './BottomAnimatedCaruosel';
export * from './FaqsSection';
export * from './LegalDocumentSection';
export * from './SupportSection';
export * from './ExperienceSection';
export * from './InfoCardsSection';
export * from './CallToActionSection1';
export * from './CallToActionSection2';
export * from './SimpleTestimonialSection';
export * from './ConvergenceAnimationSection';
export * from './QuantityInformationSection';
 